In [2]:
import pandas as pd
from jupyter_core.migrate import regex

df = pd.read_csv('rabota_it_jobs.csv')
pd.set_option('display.max_rows', None)

In [4]:
df.head()

,vacancy_id,title,company,posted_time,url
0,137139,Консультант-внедренец 1C,Casa Del Tabaco,1 minut în urmă,https://www.rabota.md/ro/locuri-de-munca/konsu...
1,137131,Программист 1С,Casa Del Tabaco,1 minut în urmă,https://www.rabota.md/ro/locuri-de-munca/progr...
2,119733,Administrator de sistem,Casa Del Tabaco,1 minut în urmă,https://www.rabota.md/ro/locuri-de-munca/admin...
3,102861,System Administrator Engineer,Arax Impex SRL,1 minut în urmă,https://www.rabota.md/ro/locuri-de-munca/syste...
4,102794,Șef Departament IT,Arax Impex SRL,1 minut în urmă,https://www.rabota.md/ro/locuri-de-munca/sef-d...

In [ ]:
df[df['title'].str.contains('[p,P]ython', regex=True)]

In [ ]:
df[df['title'].str.contains('[r,R]eact|frontend', regex=True)]

In [5]:
df[df['company'].str.contains('Stefanini', regex=True)]

,vacancy_id,title,company,posted_time,url
161,137302,C# Application Consultant Intern,Stefanini,2 ore în urmă,https://www.rabota.md/ro/locuri-de-munca/c-app...
162,136919,Mobile Engineer (Flutter),Stefanini,2 ore în urmă,https://www.rabota.md/ro/locuri-de-munca/mobil...
163,135631,C# Application Consultant,Stefanini,2 ore în urmă,https://www.rabota.md/ro/locuri-de-munca/c-app...
164,134299,Senior Java Developer,Stefanini,2 ore în urmă,https://www.rabota.md/ro/locuri-de-munca/senio...
165,133509,Support Engineer with Finnish (Level 1 - Entry...,Stefanini,2 ore în urmă,https://www.rabota.md/ro/locuri-de-munca/suppo...
166,128239,Operational System Engineer,Stefanini,2 ore în urmă,https://www.rabota.md/ro/locuri-de-munca/opera...
167,122913,Technical Support Engineer,Stefanini,2 ore în urmă,https://www.rabota.md/ro/locuri-de-munca/techn...
168,116031,Entry-Level IT Job (Training Provided),Stefanini,2 ore în urmă,https://www.rabota.md/ro/locuri-de-munca/entry...
169,36555,Technical IT Support (Entry Level),Stefanini,2 ore în urmă,https://www.rabota.md/ro/locuri-de-munca/techn...
170,135250,Start Your IT Career – English Speakers Welcom...,Stefanini,2 ore în urmă,https://www.rabota.md/ro/locuri-de-munca/start...
286,16444639,Entry-Level IT Job (Training Provided),Stefanini,2 ore în urmă,https://www.rabota.md/ro/joburi/entry-level-it...
315,16443618,Technical Support Engineer,Stefanini,2 ore în urmă,https://www.rabota.md/ro/joburi/technical-supp...
327,16442565,Operational System Engineer,Stefanini,2 ore în urmă,https://www.rabota.md/ro/joburi/operational-sy...