In [1]:
import pandas as pd
df = pd.read_csv('rabota_it_jobs_details.csv')
pd.set_option('display.max_rows', None)

In [2]:
df.head(5)

,job_title,company,location,address,description,url
0,Tehnician​-​Consultant | Administrator de sistem,Soft Lider,În locația angajatorului,NaN,Tehnician-Consultant | Administrator de sistem...,https://www.rabota.md/ro/locuri-de-munca/tehni...
1,Программист 1С | Programator 1C,Soft Lider,În locația angajatorului,NaN,Программист 1С | Programator 1C Обязанности: Р...,https://www.rabota.md/ro/locuri-de-munca/progr...
2,Administrator / Administratoare funcţional(ă) ...,Premier Energy Distribution,În locația angajatorului,NaN,ADMINISTRATOR / ADMINISTRATOARE FUNCŢIONAL(Ă) ...,https://www.rabota.md/ro/locuri-de-munca/admin...
3,IT Project Manager,Profmet Grup SRL,În locația angajatorului,"R. Moldova, mun. Chișinău, str. Petricani 31","IT Project Manager PROFMET – producător, impor...",https://www.rabota.md/ro/locuri-de-munca/it-pr...
4,Senior Data Engineer,BC Energbank SA,În locația angajatorului,NaN,Senior Data Engineer Misiunea postului Asigura...,https://www.rabota.md/ro/locuri-de-munca/senio...

In [3]:
df[df['company'].str.contains('stefanini', case=False) & df['job_title'].str.contains('Technical S', case=False)]

,job_title,company,location,address,description,url
90,Technical Support Engineer,Stefanini,În locația angajatorului,Chișinău Experiența de munca: De la 1 an Progr...,We are looking for a Technical Support Enginee...,https://www.rabota.md/ro/joburi/technical-supp...
205,Technical Support Engineer,Stefanini,În locația angajatorului,str. Sfatul Țării 29,Technical Support Engineer We are looking for ...,https://www.rabota.md/ro/locuri-de-munca/techn...

In [43]:
# fileter all jobs that require java, php, 1c
df[~df['job_title'].str.contains('java |php|ios|android|1c|c#|1С', regex=True, case=False)]

,job_title,company,location,address,description,url
0,Middle Golang Engineer,Roslin,Hibrid (Oficiu/Acasă),"182 Stefan cel Mare Street, Chisinau, Moldova",Middle Golang Engineer Roslin – Building the F...,https://www.rabota.md/ro/locuri-de-munca/middl...
1,Senior Golang Engineer,Roslin,În locația angajatorului,"182 Stefan cel Mare Street, Chisinau, Moldova",Senior Golang Engineer Roslin – Building the F...,https://www.rabota.md/ro/locuri-de-munca/senio...
4,Python Developer,Hoick,În locația angajatorului,NaN,Python Developer HOICK — международный A2P SMS...,https://www.rabota.md/ro/locuri-de-munca/pytho...
5,Expert principal – Guvernanță TIC și conformit...,Banca Națională a Moldovei,În locația angajatorului,Bulevardul Grigore Vieru 1,NaN,https://www.rabota.md/ro/locuri-de-munca/exper...
7,Преподаватель по IT ​-​ Программированию / Роб...,Nexus Insight Academy,Hibrid (Oficiu/Acasă),NaN,Преподаватель по IT - Программированию / Робот...,https://www.rabota.md/ro/locuri-de-munca/prepo...
8,Specialist Administrare Website (Turism),Panda Tur,În locația angajatorului,NaN,Specialist Administrare Website (Turism) Sunte...,https://www.rabota.md/ro/locuri-de-munca/speci...
9,"Specialist principal, Serviciul Gestionare Sof...",FinComBank - Banca de Finante si Comert SA,În locația angajatorului,NaN,"Specialist principal, Serviciul Gestionare Sof...",https://www.rabota.md/ro/locuri-de-munca/speci...
12,"Product Owner Business, Departamentul Digital ...",FinComBank - Banca de Finante si Comert SA,În locația angajatorului,NaN,"Product Owner Business, Departamentul Digital ...",https://www.rabota.md/ro/locuri-de-munca/produ...
13,"Administrator, Serviciul Administrare a Rețele...",FinComBank - Banca de Finante si Comert SA,În locația angajatorului,NaN,"Administrator, Serviciul Administrare a Rețele...",https://www.rabota.md/ro/locuri-de-munca/admin...
14,Специалист по интеграции amoCRM (Part​-​Time),Document Expert,În locația angajatorului,NaN,Специалист по интеграции amoCRM (Part-Time) Ко...,https://www.rabota.md/ro/locuri-de-munca/speci...
15,Data analyst,ARB Group,Hibrid (Oficiu/Acasă),NaN,Data analyst If you’re bold and curious and yo...,https://www.rabota.md/ro/locuri-de-munca/data-...
16,Specealist suport tehnic sisteme securitate,Q-Group Moldova | Profit din Soare,În locația angajatorului,str. Alexandru Hâjdeu 66,Specealist suport tehnic sisteme securitate Da...,https://www.rabota.md/ro/locuri-de-munca/spece...
17,IT specealist suport tehnic | 15.000-18.000 lei,Q-Group Moldova | Profit din Soare,În locația angajatorului,str. Alexandru Hâjdeu 66,IT specealist suport tehnic | 15.000-18.000 le...,https://www.rabota.md/ro/locuri-de-munca/it-sp...
18,Data & Impact Specialist,Egala by Boekestijn,În locația angajatorului,"str. Liviu Deleanu 13, Chisinau",Data & Impact Specialist Egala is not just a l...,https://www.rabota.md/ro/locuri-de-munca/data-...
19,Fullstack Developer (Node.js / NestJS / React)...,Sky.md,În locația angajatorului,"Chișinău, bd. Ștefan cel Mare și Sfînt 3",Fullstack Developer (Node.js / NestJS / React)...,https://www.rabota.md/ro/locuri-de-munca/fulls...
20,Backend Developer (Node.js 1000-2500 USD),Sky.md,În locația angajatorului,"Chișinău, bd. Ștefan cel Mare și Sfînt 3",Backend Developer (Node.js 1000-2500 USD) Sala...,https://www.rabota.md/ro/locuri-de-munca/backe...
21,Senior Front-end Developer (1000-2500 USD),Sky.md,În locația angajatorului,"Chișinău, bd. Ștefan cel Mare și Sfînt 3",Senior Front-end Developer (1000-2500 USD) Sal...,https://www.rabota.md/ro/locuri-de-munca/senio...
22,Специалист AnyKey (500-700 USD),Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Специалист AnyKey (500-700 USD) Unifun - это I...,https://www.rabota.md/ro/locuri-de-munca/speci...
23,Support Engineer (Monitoring),Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Support Engineer (Monitoring) Unifun - это IT-...,https://www.rabota.md/ro/locuri-de-munca/suppo...
25,IT Product Manager | Тирасполь - Бендеры (1500...,Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",IT Product Manager | Тирасполь - Бендеры (1500...,https://www.rabota.md/ro/locuri-de-munca/it-pr...
26,Junior IT Product Manager | Тирасполь - Бендер...,Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Junior IT Product Manager | Тирасполь - Бендер...,https://www.rabota.md/ro/locuri-de-munca/junio...
29,Middle Linux - Network Administrator | Тираспо...,Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Middle Linux - Network Administrator | Тираспо...,https://www.rabota.md/ro/locuri-de-munca/middl...
30,Junior Linux - Network Administrator | Тираспо...,Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Junior Linux - Network Administrator | Тираспо...,https://www.rabota.md/ro/locuri-de-munca/junio...
31,Junior IT Product Manager (800 USD),Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Junior IT Product Manager (800 USD) Unifun - э...,https://www.rabota.md/ro/locuri-de-munca/junio...
32,Internship IT,Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova","Internship IT Unifun - это IT-компания, котора...",https://www.rabota.md/ro/locuri-de-munca/inter...
33,Business Analyst (1500 USD),Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Business Analyst (1500 USD) Unifun - это IT-ко...,https://www.rabota.md/ro/locuri-de-munca/busin...
34,Business Process Developer (1000 USD),Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Business Process Developer (1000 USD) Unifun -...,https://www.rabota.md/ro/locuri-de-munca/busin...
36,Senior Linux - Network Administrator (2000 USD),Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Senior Linux - Network Administrator (2000 USD...,https://www.rabota.md/ro/locuri-de-munca/senio...
37,Junior Linux - Network Administrator (800 USD),Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Junior Linux - Network Administrator (800 USD)...,https://www.rabota.md/ro/locuri-de-munca/junio...
38,Middle Linux - Network System Administrator (1...,Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Middle Linux - Network System Administrator (1...,https://www.rabota.md/ro/locuri-de-munca/middl...
42,Database Administrator MSSQL/MySQL (1500 USD),Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Database Administrator MSSQL/MySQL (1500 USD) ...,https://www.rabota.md/ro/locuri-de-munca/datab...
43,IT Product Manager (1500 USD),Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",IT Product Manager (1500 USD) Unifun - это IT-...,https://www.rabota.md/ro/locuri-de-munca/it-pr...
44,Senior IT Product Manager (2000 USD),Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",Senior IT Product Manager (2000 USD) Unifun - ...,https://www.rabota.md/ro/locuri-de-munca/senio...
45,IT Product Manager (Owner - 3000 USD),Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",IT Product Manager (Owner - 3000 USD) Unifun -...,https://www.rabota.md/ro/locuri-de-munca/it-pr...
46,IT Product Manager Internship,Unifun,În locația angajatorului,"Bulevardul Decebal 6, Chișinău, Moldova",IT Product Manager Internship Unifun - это IT-...,https://www.rabota.md/ro/locuri-de-munca/it-pr...
47,DevOps Engineer,Enter,În locația angajatorului,str. Columna 170,"DevOps Engineer Esempla Systems, Chisinau Role...",https://www.rabota.md/ro/locuri-de-munca/devop...
50,Asistent administrator de sistem / Помощник си...,Nuovo Casino,În locația angajatorului,NaN,Asistent administrator de sistem / Помощник си...,https://www.rabota.md/ro/locuri-de-munca/asist...
52,Analist Securitate Cibernetică (SOC Analyst),Serviciul Tehnologia Informației și Securitate...,În locația angajatorului,NaN,Analist Securitate Cibernetică (SOC Analyst) R...,https://www.rabota.md/ro/locuri-de-munca/anali...
53,Administrator de sistem de tehnologie a inform...,Serviciul Tehnologia Informației și Securitate...,În locația angajatorului,NaN,Administrator de sistem de tehnologie a inform...,https://www.rabota.md/ro/locuri-de-munca/admin...
54,Operator monitorizare rețea și sisteme IT (ture),Serviciul Tehnologia Informației și Securitate...,În locația angajatorului,NaN,Operator monitorizare rețea și sisteme IT (tur...,https://www.rabota.md/ro/locuri-de-munca/opera...
55,Inginer suport tehnic,Serviciul Tehnologia Informației și Securitate...,În locația angajatorului,NaN,Inginer suport tehnic Cerințe : Studii: superi...,https://www.rabota.md/ro/locuri-de-munca/ingin...
56,Administrator sisteme Linux,Serviciul Tehnologia Informației și Securitate...,În locația angajatorului,NaN,Administrator sisteme Linux Cerințe : Cunoștin...,https://www.rabota.md/ro/locuri-de-munca/admin...
57,Administrator baze de date (domeniul IT),Serviciul Tehnologia Informației și Securitate...,În locația angajatorului,NaN,Administrator baze de date (domeniul IT) Cerin...,https://www.rabota.md/ro/locuri-de-munca/admin...
58,Inginer virtualizare și cloud,Serviciul Tehnologia Informației și Securitate...,În locația angajatorului,NaN,Inginer virtualizare și cloud Cerințe : Cunoșt...,https://www.rabota.md/ro/locuri-de-munca/ingin...
59,Inginer integrări continue (DevOps),Serviciul Tehnologia Informației și Securitate...,În locația angajatorului,NaN,Inginer integrări continue (DevOps) Cerințe : ...,https://www.rabota.md/ro/locuri-de-munca/ingin...
63,DevOps Engineer (AWS),Coherent Solutions,Hibrid (Oficiu/Acasă),NaN,DevOps Engineer (AWS) About Company Coherent S...,https://www.rabota.md/ro/locuri-de-munca/devop...
65,Junior .NET Developer (Strategic Hire),Coherent Solutions,Hibrid (Oficiu/Acasă),NaN,Junior .NET Developer (Strategic Hire) About C...,https://www.rabota.md/ro/locuri-de-munca/junio...
70,QA Automation Engineer (Python),Coherent Solutions,În locația angajatorului,NaN,QA Automation Engineer (Python) About Company ...,https://www.rabota.md/ro/locuri-de-munca/qa-au...
71,DevOps Engineer,Darwin,În locația angajatorului,str. Columna 170,"DevOps Engineer Esempla Systems, Chisinau Role...",https://www.rabota.md/ro/locuri-de-munca/devop...
75,AI/ML Engineer,Kapto,În locația angajatorului,NaN,"AI/ML Engineer At Kapto, we are looking for a ...",https://www.rabota.md/ro/locuri-de-munca/ai-ml...
76,System engineer / DevOps,Kapto,În locația angajatorului,NaN,System engineer / DevOps Requirements: Mandato...,https://www.rabota.md/ro/locuri-de-munca/syste...
77,.NET Developers,Kapto,În locația angajatorului,NaN,.NET Developers You will be working directly w...,https://www.rabota.md/ro/locuri-de-munca/net-d...
78,Junior+ Laravel Developer,Zazitex,În locația angajatorului,NaN,"Junior+ Laravel Developer La Zazitex , dezvolt...",https://www.rabota.md/ro/locuri-de-munca/junio...
79,Специалист AnyKey | Specialist AnyKey (500-800...,Skladovka.md,În locația angajatorului,"Кишинёв, Ботаника, ул. Буребиста 17",Специалист AnyKey | Specialist AnyKey (500-800...,https://www.rabota.md/ro/locuri-de-munca/speci...
81,System Administrator Engineer,Arax Impex SRL,În locația angajatorului,Strada Mitropolit Dosoftei 118,System Administrator Engineer Responsabilități...,https://www.rabota.md/ro/locuri-de-munca/syste...
82,Șef Departament IT,Arax Impex SRL,În locația angajatorului,Strada Mitropolit Dosoftei 118,Șef Departament IT Responsabilități: Formarea ...,https://www.rabota.md/ro/locuri-de-munca/sef-d...
83,Руководитель отдела IТ,Arax Impex SRL,În locația angajatorului,Strada Mitropolit Dosoftei 118,Руководитель отдела IТ Должностные обязанности...,https://www.rabota.md/ro/locuri-de-munca/rukov...
84,Сетевой администратор,Arax Impex SRL,În locația angajatorului,Strada Mitropolit Dosoftei 118,Сетевой администратор Основные функции: Обеспе...,https://www.rabota.md/ro/locuri-de-munca/setev...
87,"Technical Product / Delivery Manager (Fintech,...",Assist Match,În locația angajatorului,NaN,"Technical Product / Delivery Manager (Fintech,...",https://www.rabota.md/ro/locuri-de-munca/techn...
89,Tehnician​-​Consultant | Administrator de sistem,Soft Lider,În locația angajatorului,NaN,Tehnician-Consultant | Administrator de sistem...,https://www.rabota.md/ro/locuri-de-munca/tehni...
90,.NET Developer middle (продуктовая разработка),Soft Lider,În locația angajatorului,NaN,.NET Developer middle (продуктовая разработка)...,https://www.rabota.md/ro/locuri-de-munca/net-d...
92,Linux Systems Engineer (Hosting / cPanel / Pro...,Amplica,În locația angajatorului,NaN,Linux Systems Engineer (Hosting / cPanel / Pro...,https://www.rabota.md/ro/locuri-de-munca/linux...
93,Senior Network Engineer (ISP / Data Center / BGP),Amplica,În locația angajatorului,NaN,Senior Network Engineer (ISP / Data Center / B...,https://www.rabota.md/ro/locuri-de-munca/senio...
94,Middle .NET (С#) Back-end developer,Paynet Services,În locația angajatorului,"Decebal, 6",Middle .NET (С#) Back-end developer About the ...,https://www.rabota.md/ro/locuri-de-munca/middl...
95,Administrator / Administratoare funcţional(ă) ...,Premier Energy Distribution,În locația angajatorului,NaN,ADMINISTRATOR / ADMINISTRATOARE FUNCŢIONAL(Ă) ...,https://www.rabota.md/ro/locuri-de-munca/admin...
96,Amazon PPC & Media Buying Specialist,Adtelligent,Hibrid (Oficiu/Acasă),NaN,Amazon PPC & Media Buying Specialist REQUIREME...,https://www.rabota.md/ro/locuri-de-munca/amazo...
97,Computer and Telecom Engineer,MAIB,Hibrid (Oficiu/Acasă),"str. 31 August 1989, nr. 127",Computer and Telecom Engineer Căutăm un specia...,https://www.rabota.md/ro/locuri-de-munca/compu...
98,Desktop Engineer,MAIB,Hibrid (Oficiu/Acasă),"str. 31 August 1989, nr. 127",Desktop Engineer Căutăm un Desktop Engineer pr...,https://www.rabota.md/ro/locuri-de-munca/deskt...
99,Node.js Developer de la 2000 Eur,Linkair,În locația angajatorului,"str. 31 August 1989, 64",Node.js Developer de la 2000 Eur Suntem în cău...,https://www.rabota.md/ro/locuri-de-munca/nodej...
100,Experienced Manual QA Engineer,Business Class,În locația angajatorului,"Strada Mihai Viteazul 15, Chișinău 2004",Experienced Manual QA Engineer We are a US-bas...,https://www.rabota.md/ro/locuri-de-munca/exper...
101,Front End Developer (React / Next.js) de la 10...,Linkair,În locația angajatorului,"str. 31 August 1989, 64",Front End Developer (React / Next.js) de la 10...,https://www.rabota.md/ro/locuri-de-munca/front...
102,IT Network Systems Administrator,Orange Moldova,În locația angajatorului,"bd. Alba-Iulia 75, Chişinău, Moldova",IT Network Systems Administrator Orange Moldov...,https://www.rabota.md/ro/locuri-de-munca/it-ne...
103,IT Systems Support Engineer,Orange Moldova,În locația angajatorului,"bd. Alba-Iulia 75, Chişinău, Moldova",IT Systems Support Engineer Orange Moldova is ...,https://www.rabota.md/ro/locuri-de-munca/it-sy...
104,Digital Marketing Analyst,Orange Moldova,În locația angajatorului,"bd. Alba-Iulia 75, Chişinău, Moldova",Digital Marketing Analyst We are seeking a hig...,https://www.rabota.md/ro/locuri-de-munca/digit...
105,ICT Solutions Engineer,Orange Moldova,În locația angajatorului,"bd. Alba-Iulia 75, Chişinău, Moldova",ICT Solutions Engineer Orange Moldova are look...,https://www.rabota.md/ro/locuri-de-munca/ict-s...
106,Roaming Coordinator,Orange Moldova,În locația angajatorului,"bd. Alba-Iulia 75, Chişinău, Moldova",Roaming Coordinator Orange Systems is the IT h...,https://www.rabota.md/ro/locuri-de-munca/roami...
107,Telco Cloud Engineer,Orange Moldova,În locația angajatorului,"bd. Alba-Iulia 75, Chişinău, Moldova",Telco Cloud Engineer We are seeking a talented...,https://www.rabota.md/ro/locuri-de-munca/telco...
108,RPA Business Analyst,Orange Moldova,În locația angajatorului,"bd. Alba-Iulia 75, Chişinău, Moldova",RPA Business Analyst Orange Systems is the IT ...,https://www.rabota.md/ro/locuri-de-munca/rpa-b...
109,Home Internet & TV Product Expert,Orange Moldova,În locația angajatorului,"bd. Alba-Iulia 75, Chişinău, Moldova",Home Internet & TV Product Expert Orange Moldo...,https://www.rabota.md/ro/locuri-de-munca/home-...
110,Mobile Product & Offer Expert,Orange Moldova,În locația angajatorului,"bd. Alba-Iulia 75, Chişinău, Moldova",Mobile Product & Offer Expert Do you want to c...,https://www.rabota.md/ro/locuri-de-munca/mobil...
111,Manager de Vânzări ICT & IoT,Orange Moldova,În locația angajatorului,"bd. Alba-Iulia 75, Chişinău, Moldova",Manager de Vânzări ICT & IoT La O range Moldov...,https://www.rabota.md/ro/locuri-de-munca/manag...
112,RPA Developer,Orange Moldova,În locația angajatorului,"bd. Alba-Iulia 75, Chişinău, Moldova",RPA Developer Orange Systems is the IT hub of ...,https://www.rabota.md/ro/locuri-de-munca/rpa-d...
113,Специалист в отдел технической поддержки ПО,RTI,În locația angajatorului,NaN,Специалист в отдел технической поддержки ПО Тр...,https://www.rabota.md/ro/locuri-de-munca/speci...
114,Системный администратор,RTI,În locația angajatorului,NaN,Системный администратор Сфера деятельности: на...,https://www.rabota.md/ro/locuri-de-munca/siste...
115,Программист С/С++ (Linux),ADD Grup,În locația angajatorului,NaN,Программист С/С++ (Linux) Требования к кандида...,https://www.rabota.md/ro/locuri-de-munca/progr...
116,Программист MCU,ADD Grup,În locația angajatorului,NaN,Программист MCU Общие требования: Уверенное вл...,https://www.rabota.md/ro/locuri-de-munca/progr...
117,Embedded programmer,ADD Grup,În locația angajatorului,NaN,Embedded programmer Требования к кандидатам: У...,https://www.rabota.md/ro/locuri-de-munca/embed...
118,Senior Software Engineer - Backend,Parkopedia Parking Services,În locația angajatorului,"Strada Bulgară 56, Chișinău",Senior Software Engineer - Backend We’ve signe...,https://www.rabota.md/ro/locuri-de-munca/senio...
119,IT Project Manager,Profmet Grup SRL,În locația angajatorului,"R. Moldova, mun. Chișinău, str. Petricani 31","IT Project Manager PROFMET – producător, impor...",https://www.rabota.md/ro/locuri-de-munca/it-pr...
121,Principal Delivery Lead,Amdaris,În locația angajatorului,"Amdaris Moldova, Forum Office Mt. Varlaam 63/23",Principal Delivery Lead Job description: The P...,https://www.rabota.md/ro/locuri-de-munca/princ...
122,Senior AI Engineer,Amdaris,În locația angajatorului,"Amdaris Moldova, Forum Office Mt. Varlaam 63/23",Senior AI Engineer About the job We fuse toget...,https://www.rabota.md/ro/locuri-de-munca/senio...
123,Principal AI Engineer,Amdaris,În locația angajatorului,"Amdaris Moldova, Forum Office Mt. Varlaam 63/23",Principal AI Engineer About the job We fuse to...,https://www.rabota.md/ro/locuri-de-munca/princ...
124,Senior DevOps Engineer (AWS),Amdaris,În locația angajatorului,"Amdaris Moldova, Forum Office Mt. Varlaam 63/23",Senior DevOps Engineer (AWS) WE ARE AMDARIS We...,https://www.rabota.md/ro/locuri-de-munca/senio...
125,Senior Full Stack (Java+React) Developer,Amdaris,În locația angajatorului,"Amdaris Moldova, Forum Office Mt. Varlaam 63/23",Senior Full Stack (Java+React) Developer We’re...,https://www.rabota.md/ro/locuri-de-munca/senio...
126,Python Developer,BackstageIT,În locația angajatorului,"str. Columna 102, Chisinau 2012",Python Developer We are looking for a Python D...,https://www.rabota.md/ro/locuri-de-munca/pytho...
127,Full-Stack Developer,BackstageIT,În locația angajatorului,"str. Columna 102, Chisinau 2012",Full-Stack Developer We are not looking for a ...,https://www.rabota.md/ro/locuri-de-munca/full-...
128,Tekla Engineer,BackstageIT,În locația angajatorului,"str. Columna 102, Chisinau 2012",Tekla Engineer As a Structural Tekla Engineer ...,https://www.rabota.md/ro/locuri-de-munca/tekla...
129,AI Automation Engineer,BackstageIT,În locația angajatorului,"str. Columna 102, Chisinau 2012",AI Automation Engineer We’re looking for an AI...,https://www.rabota.md/ro/locuri-de-munca/ai-au...